export const  Subject = [
    {
        id:"hindi",
        name:"Hindi",
    },
    {
        id:"english",
        name:"English",
    },
    {
        id:"socialScience",
        name:"Social Science",
    },
    {
        id:"science",
        name:"Science",
    },
    {
        id:"mathematics",
        name:"Mathematics",
    },
    {
        id:"computer",
        name:"Computer",
    },
    {
        id:"chemistry",
        name:"Chemistry",
    },
    {
        id:"physics",
        name:"Physics",
    },
    {
        id:"biology",
        name:"Biology",
    },
]